### ISSUE TITLE
modifiche gestionale

### ISSUE THREAD

**Issue by pierobasile** [asterix24/GestionaleCaldaie#13]
nella schermata cliente riesci a mettere le colonne cliente e dati impianto in orizzontale anziché in verticale(come sono le verifiche per intenderci) così è di più facile lettura e non c'è tutto quello spazio vuoto sulla destra?

nelle verifiche puoi togliere "manutenzioni straordinarie" quelle vanno solo per  gli interventi!
invece sarebbe più corretto distinguere in "manutenzioni ordinaria" e "prova fumi" dove la mauntenzione ordinaria non c'e l'analisi di combistione e di conseguenza neanche il bollino. mentre per la prova fumi si. la voce prime accensioni puo stare

nella schermata principale si può avere l'ordine dei dati anche per le altre colonne? tipo per le verifiche, le manutenzioni, etc?

**Comment by asterix24** [comment]
guarda un po':

http://besalba.gestioneimpianti.net/

2013/3/14 pierobasile notifications@github.com

**Comment by pierobasile** [comment]
carino il dominio!!
quanto e costato?

Il giorno 25 marzo 2013 17:31, Daniele notifications@github.com ha
scritto:

**Comment by asterix24** [comment]
Ordine per tutte le colonne fatto.
Iniziato refactoring dell'interfaccia, correttoli vari bug, manca da pulire la classe datatotable e aggiungere qualche tasto sopra le tabelle

**Comment by asterix24** [comment]
Ripulita l'interfaccia, manca da sistemare i bottoni salva,annulla, ecc.. I messaggi e da ripulire il css.
